#!usr/bin/env bash
#install, configre and restart server

# Update package index
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create a configuration file for the redirection
cat > /etc/nginx/sites-available/redirect_me <<EOF
server {
    listen 80;
    default_server;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 404;
    }
}
EOF

# Create a symbolic link to enable the site
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Reload Nginx to apply changes
systemctl reload nginx

