#!/usr/bin/env bash
# Install Nginx
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html > /dev/null

REDIRECT_STRING="    location /redirect_me {\n        return 301 http://www.google.com;\n    }\n"

if grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    echo "Redirection rule already exists. Skipping insertion."
else
    sudo sed -i "/server {/a $REDIRECT_STRING" /etc/nginx/sites-available/default
    echo "Redirection rule added."
fi

sudo service nginx restart

