#!/usr/bin/env bash
# Install HAProxy and configure it on the system

# Update package repositories
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Start and enable HAProxy service
sudo service haproxy start
sudo service haproxy enable

# Define the configuration file path
FILE=/etc/haproxy/haproxy.cfg

# Add configuration to the HAProxy configuration file
echo -e "frontend web-frontend
\tbind *:80
\tmode http
\tdefault_backend web_backend
backend web_backend
\tmode http
\tbalance roundrobin
\tserver 20344-web-01 100.25.201.110:80 check
\tserver 20344-web-02 100.26.231.151:80 check" | sudo tee $FILE

# Restart HAProxy service if configuration is updated
sudo service haproxy reload

