#!/usr/bin/env bash
#displays Best School 10 times.
#for ((i=1; i<=10; i++));
#do 
#"Best School"
#done
#!/usr/bin/env bash
# Displays "Best School" 10 times using a for loop.

for (( i=0; i<10; i++ ))
do
  echo "Best School"
done
