#!/usr/bin/env bash
#prints time 12 hrs and 59 minutes
hours=0
while [ $hours -le 12 ] ; do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -le 59 ] ; do
		echo "$minutes"
		((minutes += 1))
	done
	((hours += 1))
done
