#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Create a backup of the original hosts file
cp /etc/hosts /etc/hosts_backup

# Modify the hosts file to set up desired configurations
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new

# Replace the original hosts file with the updated one
sudo cp -f ~/hosts.new /etc/hosts

